apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 959525231662.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 959525231662.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: 52c94411
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
